import { BaseRule } from "../analysis/rule";
import { PromptIssue, RuleContext } from "../types";

const contains = (text: string, pattern: RegExp): boolean => pattern.test(text);
export class MissingRoleRule extends BaseRule { readonly id="missing-role"; readonly category="context" as const; analyze(c: RuleContext): PromptIssue[] { return contains(c.prompt, /\b(act as|you are|as a)\b/i) ? [] : [this.issue("Missing role definition", "The model has no explicit perspective or expertise to adopt.", "warning", "Start with a role, such as ‘You are a senior technical writer.’")]; } }
export class MissingOutputRule extends BaseRule { readonly id="missing-output-format"; readonly category="formatting" as const; analyze(c: RuleContext): PromptIssue[] { return contains(c.prompt, /\b(json|table|markdown|bullet|format|structure|schema)\b/i) ? [] : [this.issue("No output format", "Expected output is not structured, making responses less predictable.", "warning", "Specify a format: headings, bullets, table, JSON schema, or word limit.")]; } }
export class AmbiguityRule extends BaseRule { readonly id="ambiguous-language"; readonly category="specificity" as const; analyze(c: RuleContext): PromptIssue[] { const match=/\b(nice|good|better|appropriate|quickly|some|things|etc\.?|maybe)\b/i.exec(c.prompt); return match ? [this.issue("Ambiguous wording", `“${match[0]}” is subjective and leaves room for interpretation.`, "warning", "Replace subjective terms with measurable requirements.", 0, match.index, match.index + match[0].length)] : []; } }
export class WeakVerbRule extends BaseRule { readonly id="weak-verbs"; readonly category="specificity" as const; analyze(c: RuleContext): PromptIssue[] { const match=/\b(help|handle|do|make|fix|improve)\b/i.exec(c.prompt); return match ? [this.issue("Weak instruction verb", `“${match[0]}” does not precisely describe the requested outcome.`, "info", "Use a precise verb such as analyze, compare, draft, classify, or validate.", 0, match.index, match.index+match[0].length)] : []; } }
export class RepetitionRule extends BaseRule { readonly id="repeated-information"; readonly category="efficiency" as const; analyze(c: RuleContext): PromptIssue[] { const seen=new Set<string>(); const repeated=c.words.find(w => w.length>5 && (seen.has(w.toLowerCase()) || !seen.add(w.toLowerCase()))); return repeated ? [this.issue("Potential repetition", `“${repeated}” appears more than once and may be redundant.`, "info", "Remove duplicated context unless repetition is intentional.", 4)] : []; } }
export class MissingConstraintsRule extends BaseRule { readonly id="missing-constraints"; readonly category="constraints" as const; analyze(c: RuleContext): PromptIssue[] { return contains(c.prompt,/\b(must|must not|only|limit|avoid|under|at most)\b/i) ? [] : [this.issue("Missing constraints", "No boundaries were found for scope, length, tone, or exclusions.", "warning", "Add explicit constraints, e.g. audience, length, scope, and exclusions.")]; } }
export class MissingExamplesRule extends BaseRule { readonly id="missing-examples"; readonly category="examples" as const; analyze(c: RuleContext): PromptIssue[] { return contains(c.prompt,/\b(example|e\.g\.|for instance|input:|output:)\b/i) ? [] : [this.issue("No examples provided", "Examples can substantially improve consistency for nuanced tasks.", "info", "Add one concise input/output example for complex or style-sensitive tasks.")]; } }
export class SafetyRule extends BaseRule { readonly id="prompt-injection"; readonly category="safety" as const; analyze(c: RuleContext): PromptIssue[] { const match=/\b(ignore (previous|all)|reveal (your|the) instructions|system prompt|bypass)\b/i.exec(c.prompt); return match ? [this.issue("Prompt injection pattern", "This text resembles an instruction-override attempt.", "error", "Remove instruction-override language and isolate untrusted content.", 0, match.index, match.index+match[0].length)] : []; } }
export class SecretRule extends BaseRule { readonly id="secret-leakage"; readonly category="safety" as const; analyze(c: RuleContext): PromptIssue[] { const match=/(sk-[A-Za-z0-9_-]{12,}|AKIA[0-9A-Z]{16}|-----BEGIN (?:RSA |OPENSSH )?PRIVATE KEY-----)/.exec(c.prompt); return match ? [this.issue("Possible secret detected", "The prompt appears to contain credential material.", "error", "Remove and rotate the secret; reference it through a secure mechanism instead.", 0, match.index, match.index+match[0].length)] : []; } }
export class PiiRule extends BaseRule { readonly id="pii-detection"; readonly category="safety" as const; analyze(c: RuleContext): PromptIssue[] { const match=/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b|\b(?:\d[ -]*?){13,16}\b/.exec(c.prompt); return match ? [this.issue("Possible PII detected", "The prompt contains an email address or payment-card-like number.", "warning", "Redact or tokenize personal data before sending it to a model.", 0, match.index, match.index+match[0].length)] : []; } }
export const builtinRules = [MissingRoleRule, MissingOutputRule, AmbiguityRule, WeakVerbRule, RepetitionRule, MissingConstraintsRule, MissingExamplesRule, SafetyRule, SecretRule, PiiRule];
