import * as vscode from "vscode";
import { AnalysisResult } from "../types";

export class PromptChatPanel {
  private panel?: vscode.WebviewPanel;
  constructor(private readonly onSubmit: (prompt: string) => Promise<AnalysisResult | undefined>) {}
  show(): void {
    if (!this.panel) { this.panel = vscode.window.createWebviewPanel("promptguard.chat", "PromptGuard Chat", vscode.ViewColumn.Beside, { enableScripts: true }); this.panel.onDidDispose(() => { this.panel = undefined; }); this.panel.webview.onDidReceiveMessage(async (message: unknown) => { const prompt = typeof message === "object" && message !== null ? (message as { prompt?: unknown }).prompt : undefined; if (typeof prompt !== "string") return; const result = await this.onSubmit(prompt); this.panel?.webview.postMessage({ type: "result", result: result ? { score: result.score.total, grade: result.score.grade, issues: result.issues.map(issue => ({ title: issue.title, fix: issue.suggestedFix })) } : undefined }); }); }
    this.panel.webview.html = `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);padding:22px;color:var(--vscode-foreground)}textarea{box-sizing:border-box;width:100%;min-height:150px;padding:12px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border);border-radius:7px;font:inherit}button{margin-top:10px;background:#0e639c;color:#fff;border:0;border-radius:5px;padding:8px 14px;font:inherit}.hint{color:var(--vscode-descriptionForeground)}li{margin:9px 0}</style></head><body><h1>PromptGuard Chat</h1><p class="hint">Local analysis. Press Enter to analyze; use Shift+Enter for a new line.</p><textarea id="prompt" placeholder="Write or paste a prompt…"></textarea><br><button id="analyze">Analyze prompt</button><section id="result"></section><script>const v=acquireVsCodeApi(),p=document.getElementById('prompt'),r=document.getElementById('result');function submit(){if(p.value.trim())v.postMessage({prompt:p.value})}document.getElementById('analyze').onclick=submit;p.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}});window.addEventListener('message',e=>{const d=e.data;if(d.type==='result'){r.innerHTML=d.result?'<h2>'+d.result.score+'/100 · '+d.result.grade+'</h2><ul>'+d.result.issues.map(i=>'<li><strong>'+i.title+'</strong><br>'+i.fix+'</li>').join('')+'</ul>':'<p>No analysis result.</p>'}})</script></body></html>`;
    this.panel.reveal();
  }
}
