import * as vscode from "vscode";
import { RefinementAction, RefinementPlan, RefinementResult } from "../improver/refinementService";

export class RefinementPanel {
  private panel?: vscode.WebviewPanel;
  constructor(private readonly plan: (prompt: string, action: RefinementAction) => Promise<RefinementPlan>, private readonly run: (prompt: string, answers: Readonly<Record<string, string>>, action: RefinementAction) => Promise<RefinementResult>) {}
  async show(prompt: string, action: RefinementAction): Promise<void> {
    const panel = this.panel ??= vscode.window.createWebviewPanel("promptguard.refine", "PromptGuard", vscode.ViewColumn.Beside, { enableScripts: true });
    panel.onDidDispose(() => { this.panel = undefined; }); panel.webview.html = this.loadingHtml(); panel.reveal();
    try { const plan = await this.plan(prompt, action); panel.webview.html = this.actionHtml(plan); panel.webview.onDidReceiveMessage(async (message: unknown) => { if (!this.isSubmit(message)) return; panel.webview.html = this.loadingHtml("Processing your prompt..."); try { panel.webview.html = this.resultHtml(await this.run(prompt, message.answers, action)); } catch (error) { panel.webview.html = this.errorHtml(error); } }); } catch (error) { panel.webview.html = this.errorHtml(error); }
  }
  private isSubmit(message: unknown): message is { type: "submit"; answers: Record<string, string> } { return typeof message === "object" && message !== null && (message as { type?: unknown }).type === "submit" && typeof (message as { answers?: unknown }).answers === "object" && (message as { answers?: unknown }).answers !== null; }
  private loadingHtml(text = "Preparing PromptGuard..."): string { return `<!doctype html><body style="font-family:var(--vscode-font-family);padding:24px"><h2>PromptGuard</h2><p>${text}</p></body>`; }
  private errorHtml(error: unknown): string { return `<!doctype html><body style="font-family:var(--vscode-font-family);padding:24px"><h2>PromptGuard</h2><p>${error instanceof Error ? error.message : "Unable to process this prompt."}</p></body>`; }
  private actionHtml(plan: RefinementPlan): string {
    const data = JSON.stringify(plan.questions).replace(/</g, "\\u003c"); const titles: Record<RefinementAction, string> = { cleanup: "Offline safe cleanup", expand: "Expand prompt", minimize: "Minimize token usage" }; const descriptions: Record<RefinementAction, string> = { cleanup: "Local and reversible. Removes exact duplicate lines and safe boilerplate only.", expand: `${plan.questions.length} Groq-selected clarification questions. Answer as many as apply; unused questions may be left blank.`, minimize: "Groq will minimize tokens while preserving explicit requirements. If it cannot prove a smaller safe result, PromptGuard returns the original." };
    return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);padding:24px;max-width:760px}fieldset{margin:15px 0;border:1px solid var(--vscode-widget-border);border-radius:8px;padding:14px}label{display:block;padding:5px 0}input[type=text]{width:96%;margin-top:7px;padding:7px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border)}button{background:#0e639c;color:#fff;border:0;border-radius:5px;padding:9px 14px;font:inherit}.hint{color:var(--vscode-descriptionForeground)}</style></head><body><h1>${titles[plan.action]}</h1><p class="hint">${descriptions[plan.action]}</p><form id="form"></form><button id="run">${plan.action === "expand" ? "Generate clearer prompt" : plan.action === "minimize" ? "Minimize tokens" : "Clean up safely"}</button><script>const vscode=acquireVsCodeApi(),questions=${data},form=document.getElementById('form');form.innerHTML=questions.map(q=>'<fieldset><legend><strong>'+q.question+'</strong></legend>'+q.options.map((o,j)=>'<label><input type="radio" name="'+q.id+'" value="'+o.replace(/"/g,'&quot;')+'" '+(j===0?'checked':'')+'> '+o+'</label>').join('')+'<input type="text" id="'+q.id+'-other" placeholder="Other (optional)"></fieldset>').join('');document.getElementById('run').onclick=()=>{const answers={},data=new FormData(form);questions.forEach(q=>{const selected=data.get(q.id),other=document.getElementById(q.id+'-other').value.trim();answers[q.id]=other||selected||''});vscode.postMessage({type:'submit',answers})}</script></body></html>`;
  }
  private resultHtml(result: RefinementResult): string { const safe = JSON.stringify(result.prompt).replace(/</g, "\\u003c"); const status = result.fellBack ? "No smaller safe version was found; original retained." : `${result.sourceTokens} → ${result.resultTokens} estimated tokens`; return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);padding:24px;max-width:760px}pre{white-space:pre-wrap;background:var(--vscode-textCodeBlock-background);padding:14px;border-radius:8px}.hint{color:var(--vscode-descriptionForeground)}button{background:#0e639c;color:#fff;border:0;border-radius:5px;padding:9px 14px;font:inherit}</style></head><body><h1>Prompt result</h1><p class="hint">${status}</p><pre id="prompt"></pre><button id="copy">Copy prompt</button><script>const prompt=${safe};document.getElementById('prompt').textContent=prompt;document.getElementById('copy').onclick=()=>navigator.clipboard.writeText(prompt)</script></body></html>`; }
}
