import * as vscode from "vscode";
import { RefinementPlan } from "../improver/refinementService";

export class RefinementPanel {
  private panel?: vscode.WebviewPanel;
  constructor(private readonly plan: (prompt: string) => Promise<RefinementPlan>, private readonly refine: (prompt: string, answers: Readonly<Record<string, string>>) => Promise<string>) {}
  async show(prompt: string): Promise<void> {
    const panel = this.panel ??= vscode.window.createWebviewPanel("promptguard.refine", "PromptGuard: Improve Prompt", vscode.ViewColumn.Beside, { enableScripts: true });
    panel.onDidDispose(() => { this.panel = undefined; });
    panel.webview.html = this.loadingHtml(); panel.reveal();
    try { const plan = await this.plan(prompt); panel.webview.html = this.questionHtml(panel.webview, prompt, plan); panel.webview.onDidReceiveMessage(async (message: unknown) => { if (!this.isAnswersMessage(message)) return; panel.webview.html = this.loadingHtml("Refining your prompt…"); try { const improved = await this.refine(prompt, message.answers); panel.webview.html = this.resultHtml(panel.webview, improved); } catch (error) { panel.webview.html = this.errorHtml(error); } }); } catch (error) { panel.webview.html = this.errorHtml(error); }
  }
  private isAnswersMessage(message: unknown): message is { type: "answers"; answers: Record<string, string> } { return typeof message === "object" && message !== null && (message as { type?: unknown }).type === "answers" && typeof (message as { answers?: unknown }).answers === "object" && (message as { answers?: unknown }).answers !== null; }
  private loadingHtml(text = "Finding the fewest questions that will improve your prompt…"): string { return `<!doctype html><body style="font-family:var(--vscode-font-family);padding:24px"><h2>PromptGuard</h2><p>${text}</p></body>`; }
  private errorHtml(error: unknown): string { const text = error instanceof Error ? error.message : "Unable to reach Groq."; return `<!doctype html><body style="font-family:var(--vscode-font-family);padding:24px"><h2>PromptGuard</h2><p>${text}</p></body>`; }
  private questionHtml(webview: vscode.Webview, prompt: string, plan: RefinementPlan): string { const data = JSON.stringify(plan.questions).replace(/</g, "\\u003c"); const promptData = JSON.stringify(prompt).replace(/</g, "\\u003c"); return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);padding:24px;max-width:760px}fieldset{margin:16px 0;border:1px solid var(--vscode-widget-border);border-radius:8px;padding:14px}label{display:block;padding:6px 0}input[type=text]{width:96%;margin:7px 0;padding:7px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border)}button{background:#0e639c;color:white;border:0;border-radius:5px;padding:9px 14px;font:inherit}.hint{color:var(--vscode-descriptionForeground)}</style></head><body><h1>Clarify only what matters</h1><p class="hint">${plan.questions.length} questions · planning cost $${plan.costUsd.toFixed(6)} · no calls while you choose</p><form id="form"></form><button id="go">Create improved prompt</button><script>const vscode=acquireVsCodeApi(),questions=${data},original=${promptData},form=document.getElementById('form');form.innerHTML=questions.map((q,i)=>'<fieldset><legend><strong>'+q.question+'</strong></legend>'+q.options.map((o,j)=>'<label><input required type="radio" name="'+q.id+'" value="'+o.replace(/"/g,'&quot;')+'" '+(j===0?'checked':'')+'> '+o+'</label>').join('')+'<input type="text" id="'+q.id+'-other" placeholder="If you selected Other, describe it here">'+'</fieldset>').join('');document.getElementById('go').onclick=()=>{const answers={},data=new FormData(form);questions.forEach(q=>{const choice=data.get(q.id),other=document.getElementById(q.id+'-other').value.trim();answers[q.id]=choice==='Other (describe below)'&&other?other:choice});vscode.postMessage({type:'answers',answers,original})}</script></body></html>`; }
  private resultHtml(webview: vscode.Webview, prompt: string): string { const safe = JSON.stringify(prompt).replace(/</g, "\\u003c"); return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);padding:24px;max-width:760px}pre{white-space:pre-wrap;background:var(--vscode-textCodeBlock-background);padding:14px;border-radius:8px}button{background:#0e639c;color:#fff;border:0;border-radius:5px;padding:9px 14px;font:inherit}</style></head><body><h1>Improved prompt</h1><pre id="prompt"></pre><button id="copy">Copy prompt</button><script>const prompt=${safe};document.getElementById('prompt').textContent=prompt;document.getElementById('copy').onclick=()=>navigator.clipboard.writeText(prompt)</script></body></html>`; }
}
