import * as vscode from "vscode";
import { PromptAnalyzer } from "./analysis/promptAnalyzer";
import { getSettings } from "./config/settings";
import { Dashboard } from "./dashboard/dashboard";
import { HistoryStore } from "./history/historyStore";
import { AnalysisResult } from "./types";
import { IssueDecorations } from "./ui/decorations";
import { NavigatorProvider } from "./ui/navigator";
import { PromptGuardCodeActions } from "./commands/registerCodeActions";
import { PromptGuardParticipant } from "./chat/promptGuardParticipant";
import { GroqGateway } from "./integrations/groq/groqGateway";
import { PromptChatPanel } from "./ui/promptChatPanel";
import { RefinementService } from "./improver/refinementService";
import { RefinementPanel } from "./ui/refinementPanel";
import { GroqModelProvider } from "./integrations/groq/groqModelProvider";
import { GroqClient } from "./integrations/groq/groqClient";

export function activate(context: vscode.ExtensionContext): void {
  const analyzer = new PromptAnalyzer(); const history = new HistoryStore(context.workspaceState); const groqClient = new GroqClient(context.extensionUri.fsPath); const groq = new GroqGateway(groqClient); const refinements = new RefinementService(groq); const decorations = new IssueDecorations(); const navigator = new NavigatorProvider(); let lastResult: AnalysisResult | undefined;
  const enrichWithGroqJudgement = async (result: AnalysisResult): Promise<AnalysisResult> => { if (!await groq.isConfigured()) { result.groqStatus = "Groq not configured — score is local-only."; return result; } try { const judgement = await groq.judge(result.prompt, result.issues.map(issue => `${issue.title}: ${issue.description}`)); result.score.total = judgement.score; result.score.grade = judgement.score >= 85 ? "Excellent" : judgement.score >= 70 ? "Strong" : judgement.score >= 50 ? "Needs work" : "At risk"; result.scoreSource = "groq"; result.groqStatus = "Groq semantic judgement applied."; result.issues.unshift({ id: "groq-semantic-judgement", ruleId: "groq-semantic-judgement", title: "Groq semantic assessment", description: judgement.rationale, severity: judgement.score < 50 ? "warning" : "info", confidence: 0.9, category: "specificity", suggestedFix: "Address the missing context identified by the semantic assessment.", estimatedTokenSavings: 0, estimatedCostSavings: judgement.costUsd }); } catch (error) { result.groqStatus = `Groq judgement unavailable — local-only score (${error instanceof Error ? error.message : "unknown error"}).`; } return result; };
  const improve = async (): Promise<void> => { if (!lastResult) { vscode.window.showInformationMessage("Analyze a prompt before requesting an improvement."); return; } const panel = new RefinementPanel(prompt => refinements.plan(prompt), async (prompt, answers) => (await refinements.refine(prompt, answers)).prompt); await panel.show(lastResult.prompt); };
  const dashboard = new Dashboard(context.extensionUri, () => { void improve(); });
  const localChat = new PromptChatPanel(async prompt => { const settings = getSettings(); if (prompt.trim().length < settings.minimumPromptLength) { vscode.window.showInformationMessage("PromptGuard: Enter a longer prompt to analyze."); return undefined; } lastResult = await enrichWithGroqJudgement(analyzer.analyze(prompt, settings.disabledRules)); await history.add({ id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, timestamp: lastResult.analyzedAt, originalPrompt: prompt, optimizedPrompt: lastResult.optimization.optimizedPrompt, score: lastResult.score.total, improvement: Math.max(0, 100 - lastResult.score.total), estimatedSavings: lastResult.cost.potentialSavingsUsd ?? 0 }); navigator.refresh(); dashboard.show(lastResult, history.list()); return lastResult; });
  const activeText = (): { editor: vscode.TextEditor; text: string } | undefined => { const editor=vscode.window.activeTextEditor; if (!editor) return undefined; const selection=editor.selection; return { editor, text: selection.isEmpty ? editor.document.getText() : editor.document.getText(selection) }; };
  const analyze = async (): Promise<void> => { const target=activeText(); const settings=getSettings(); if (!target || !settings.enabled) return; if (target.text.trim().length < settings.minimumPromptLength) { vscode.window.showInformationMessage("PromptGuard: Select a prompt with more content to analyze."); return; } lastResult=await enrichWithGroqJudgement(analyzer.analyze(target.text, settings.disabledRules)); decorations.apply(target.editor,lastResult.issues); await history.add({ id: `${Date.now()}-${Math.random().toString(36).slice(2,7)}`, timestamp:lastResult.analyzedAt, originalPrompt:target.text, optimizedPrompt:lastResult.optimization.optimizedPrompt, score:lastResult.score.total, improvement:Math.max(0,100-lastResult.score.total), estimatedSavings:lastResult.cost.potentialSavingsUsd ?? 0 }); navigator.refresh(); vscode.window.showInformationMessage(`PromptGuard: ${lastResult.score.total}/100 · ${lastResult.issues.length} finding${lastResult.issues.length===1?"":"s"}`); dashboard.show(lastResult,history.list()); };
  const optimize = async (): Promise<void> => { if (!lastResult) await analyze(); if (!lastResult) return; const original = vscode.window.activeTextEditor?.document.uri; if (!original) return; const optimized = await vscode.workspace.openTextDocument({ content:lastResult.optimization.optimizedPrompt, language:"markdown" }); await vscode.commands.executeCommand("vscode.diff", original, optimized.uri, "PromptGuard: Optimization Preview"); };
  const chat = new PromptGuardParticipant(analyzer, getSettings, async (result, entry) => { lastResult = await enrichWithGroqJudgement(result); entry.score = lastResult.score.total; await history.add(entry); navigator.refresh(); });
  const participant = vscode.chat.createChatParticipant("promptguard.analyzer", (request, chatContext, stream, token) => chat.handle(request, chatContext, stream, token));
  participant.iconPath = vscode.Uri.joinPath(context.extensionUri, "resources", "promptguard.svg");
  const groqProvider = vscode.lm.registerLanguageModelChatProvider("promptguard-groq", new GroqModelProvider(groqClient));
  context.subscriptions.push(decorations, participant, groqProvider, vscode.window.registerTreeDataProvider("promptguard.navigator",navigator), vscode.languages.registerCodeActionsProvider({ scheme: "file" }, new PromptGuardCodeActions(), { providedCodeActionKinds: PromptGuardCodeActions.providedCodeActionKinds }), vscode.commands.registerCommand("promptguard.analyze",analyze), vscode.commands.registerCommand("promptguard.optimize",optimize), vscode.commands.registerCommand("promptguard.improve",improve), vscode.commands.registerCommand("promptguard.openChat",()=>localChat.show()), vscode.commands.registerCommand("promptguard.configureGroq",()=>vscode.window.showInformationMessage("Create .env from .env.example and add a newly generated GROQ_API_KEY, then reload VS Code.")), vscode.commands.registerCommand("promptguard.openDashboard",()=>dashboard.show(lastResult,history.list())), vscode.commands.registerCommand("promptguard.showHistory",async()=>{const entry=await vscode.window.showQuickPick(history.list().map(item=>({label:`${item.score}/100 · ${new Date(item.timestamp).toLocaleDateString()}`,description:item.originalPrompt.slice(0,90),item})),{placeHolder:"Search your local PromptGuard history"}); if(entry){const doc=await vscode.workspace.openTextDocument({content:entry.item.originalPrompt,language:"markdown"}); await vscode.window.showTextDocument(doc);}}), vscode.commands.registerCommand("promptguard.openSettings",()=>vscode.commands.executeCommand("workbench.action.openSettings","@ext:promptguard")), vscode.workspace.onDidSaveTextDocument(document=>{if(getSettings().analyzeOnSave && vscode.window.activeTextEditor?.document===document) void analyze();}));
}
export function deactivate(): void {}
